apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://github.com/DevopsNaratel/Deployment-Manifest-App.git
    targetRevision: HEAD
    path: bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
