apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ include "base-chart.name" . }}
  namespace: {{ if eq .Values.app.env "testing" }}testing{{ else }}{{ .Values.app.id }}-{{ .Values.app.name }}{{ end }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretData }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}