#apiVersion: v1
#kind: Secret
#metadata:
#  name: secret-{{ include "base-chart.name" . }}
#  labels:
#    {{- include "base-chart.labels" . | nindent 4 }}
#type: Opaque
#data:
#  {{- range $key, $val := .Values.secretData }}
#  {{ $key }}: {{ $val | b64enc | quote }}
#  {{- end }}


apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ include "base-chart.name" . }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
  annotations:
    # WAJIB: Agar AVP melakukan dekripsi SOPS
    avp.plugin.com/path: "avp-sops"
type: Opaque
stringData: # Gunakan stringData untuk nilai plain-text (akan di-encode otomatis oleh K8s)
  {{- range $key, $val := .Values.secretData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
