apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ include "base-chart.name" . }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secretData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
