apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-{{ include "base-chart.name" . }}
  namespace: {{ if eq .Values.app.env "testing" }}testing{{ else }}{{ .Values.app.id }}-{{ .Values.app.name | replace "-db" "" }}{{ end }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
spec:
  serviceName: svc-{{ include "base-chart.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/id: {{ .Values.app.id | quote }}
      app.kubernetes.io/name: {{ .Values.app.name | quote }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ toYaml .Values.secretData | sha256sum }}
      labels:
        {{- include "base-chart.labels" . | nindent 8 }}
    spec:
      containers:
      - name: db
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        
        {{- if eq .Values.backup.type "postgres" }}
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgresUser | default "postgres" }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgresUser | default "postgres" }}
          initialDelaySeconds: 15
          periodSeconds: 20
        {{- else }}
        readinessProbe:
          exec:
            command: ["sh", "-c", "mysqladmin ping -h localhost"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["sh", "-c", "mysqladmin ping -h localhost"]
          initialDelaySeconds: 15
          periodSeconds: 20
        {{- end }}

        envFrom:
        - secretRef:
            name: secret-{{ include "base-chart.name" . }}
        volumeMounts:
        - name: data
          {{- if eq .Values.backup.type "postgres" }}
          mountPath: /var/lib/postgresql/data
          subPath: postgres
          {{- else }}
          mountPath: /var/lib/mysql
          subPath: mysql
          {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.storageClassName | default "longhorn" }}
      resources:
        requests:
          storage: {{ .Values.storage.size | default "1Gi" }}
