apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-backend-test
  namespace: cicd
spec:
  project: default
  source:
    # URL disinkronkan dengan menu Settings (Tanpa "/" di akhir)
    repoURL: https://github.com/DevopsNaratel/Deployment-Manifest-App
    targetRevision: main # Menggunakan branch eksplisit untuk menghindari error resolusi HEAD
    path: example-backend/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: 999-testing-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
