apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: cicd
spec:
  template:
    spec:
      volumes:
        - name: var-files
          emptyDir: {}
        - name: plugins-dir # Volume khusus untuk socket plugin
          emptyDir: {}
        - name: custom-tools # Volume untuk menyimpan sops & plugins
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age-key
        - name: cmp-plugin
          configMap:
            name: cmp-plugin
      
      initContainers:
        - name: install-tools
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache ca-certificates wget tar
              # Install SOPS
              wget -O /custom-tools/sops https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
              chmod +x /custom-tools/sops
              
              # Install Helm Secrets
              wget -O /tmp/helm-secrets.tar.gz https://github.com/jkroepke/helm-secrets/releases/download/v4.6.0/helm-secrets.tar.gz
              mkdir -p /custom-tools/helm-plugins/helm-secrets
              tar -zxf /tmp/helm-secrets.tar.gz -C /custom-tools/helm-plugins/helm-secrets
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools

      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins-dir # Pisahkan disini
        
        - name: helm-secrets
          image: quay.io/argoproj/argocd:v2.11.0 # Gunakan image resmi
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Tambahkan path tools ke PATH sistem
              export PATH=$PATH:/custom-tools
              argocd-cmp-server --loglevel debug
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /helm-secrets/keys.txt
            - name: HELM_PLUGINS
              value: /custom-tools/helm-plugins
            - name: SOPS_BINARY
              value: /custom-tools/sops
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins-dir # Pisahkan disini
            - mountPath: /custom-tools
              name: custom-tools
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: cmp-plugin
            - mountPath: /helm-secrets/keys.txt
              subPath: keys.txt
              name: sops-age