apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: cicd
spec:
  template:
    spec:
      volumes:
        - name: var-files
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age-key
        - name: cmp-plugin
          configMap:
            name: cmp-plugin
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
        - name: helm-secrets
          image: devopsnaratel/argocd-vault-plugin:v1.18.1
          command:
            - "/bin/sh"
            - "-c"
            - |
              chmod +x /var/run/argocd/argocd-cmp-server
              /var/run/argocd/argocd-cmp-server --loglevel debug --logformat json
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /helm-secrets/keys.txt
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: cmp-plugin
            - mountPath: /helm-secrets/keys.txt
              subPath: keys.txt
              name: sops-age
